{"uid":"7f675bfbcaba31bf","name":"test_edit","fullName":"tests.test_edit#test_edit","historyId":"65f16bf3ba35b152446354b19e0b1751","time":{"start":1717884462953,"stop":1717884462953,"duration":0},"status":"broken","statusMessage":"NameError: name 'fake' is not defined","statusTrace":"chrome_browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"d7bd4da987b34498e56f298ec20d3564\")>\n\n    @pytest.fixture\n    def logged_in_test(chrome_browser: webdriver):\n>       user = setup_test_user()\n\ntests/conftest.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/conftest.py:44: in setup_test_user\n    user = get_random_user()\ngenerators/user_generator.py:44: in get_random_user\n    username = generate_username()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def generate_username() -> str:\n>       username = fake.user_name()\nE       NameError: name 'fake' is not defined\n\ngenerators/user_generator.py:28: NameError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1717884460231,"stop":1717884460248,"duration":17},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"chrome_browser","time":{"start":1717884462953,"stop":1717884463281,"duration":328},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"logged_in_test","time":{"start":1717884463281,"stop":1717884463281,"duration":0},"status":"broken","statusMessage":"NameError: name 'fake' is not defined\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-e2e-localstack-tests/python-e2e-localstack-tests/tests/conftest.py\", line 35, in logged_in_test\n    user = setup_test_user()\n           ^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-e2e-localstack-tests/python-e2e-localstack-tests/tests/conftest.py\", line 44, in setup_test_user\n    user = get_random_user()\n           ^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-e2e-localstack-tests/python-e2e-localstack-tests/generators/user_generator.py\", line 44, in get_random_user\n    username = generate_username()\n               ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/python-e2e-localstack-tests/python-e2e-localstack-tests/generators/user_generator.py\", line 28, in generate_username\n    username = fake.user_name()\n               ^^^^\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"status":"broken","statusMessage":"NameError: name 'fake' is not defined","statusTrace":"chrome_browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"d7bd4da987b34498e56f298ec20d3564\")>\n\n    @pytest.fixture\n    def logged_in_test(chrome_browser: webdriver):\n>       user = setup_test_user()\n\ntests/conftest.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ntests/conftest.py:44: in setup_test_user\n    user = get_random_user()\ngenerators/user_generator.py:44: in get_random_user\n    username = generate_username()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def generate_username() -> str:\n>       username = fake.user_name()\nE       NameError: name 'fake' is not defined\n\ngenerators/user_generator.py:28: NameError","steps":[],"attachments":[{"uid":"8174bbf526ca666c","name":"log","source":"8174bbf526ca666c.txt","type":"text/plain","size":355}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true},"afterStages":[{"name":"chrome_browser::0","time":{"start":1717884463291,"stop":1717884463349,"duration":58},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_edit"},{"name":"host","value":"fv-az1055-767"},{"name":"thread","value":"3459-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_edit"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":11,"unknown":0,"total":13},"items":[{"uid":"30ab46a929868bb4","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/8//#testresult/30ab46a929868bb4","status":"passed","time":{"start":1717883299641,"stop":1717883302135,"duration":2494}},{"uid":"e9a7dd8ca42ffc85","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/7//#testresult/e9a7dd8ca42ffc85","status":"broken","statusDetails":"TypeError: Object of type Response is not JSON serializable","time":{"start":1717776859625,"stop":1717776859625,"duration":0}},{"uid":"f9bb3c18e4d42142","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/6//#testresult/f9bb3c18e4d42142","status":"passed","time":{"start":1717766807053,"stop":1717766809626,"duration":2573}},{"uid":"70916daa24a8b64","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/5//#testresult/70916daa24a8b64","status":"passed","time":{"start":1717765031900,"stop":1717765034165,"duration":2265}},{"uid":"77616e31c325c604","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/2//#testresult/77616e31c325c604","status":"passed","time":{"start":1717612972930,"stop":1717612975550,"duration":2620}},{"uid":"8aa2f8130b9bc89f","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/1//#testresult/8aa2f8130b9bc89f","status":"passed","time":{"start":1715622178057,"stop":1715622180769,"duration":2712}},{"uid":"f52004bc57c20eba","reportUrl":"https://urszulamaciag.github.io/python-e2e-localstack-tests/1//#testresult/f52004bc57c20eba","status":"passed","time":{"start":1715618610355,"stop":1715618612852,"duration":2497}},{"uid":"4315eee87b4387e3","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/26//#testresult/4315eee87b4387e3","status":"passed","time":{"start":1715529066079,"stop":1715529068717,"duration":2638}},{"uid":"96b80df7b489dd81","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/25//#testresult/96b80df7b489dd81","status":"passed","time":{"start":1715528273523,"stop":1715528276262,"duration":2739}},{"uid":"72bb14d6f65bbaf9","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/24//#testresult/72bb14d6f65bbaf9","status":"passed","time":{"start":1715499474259,"stop":1715499476933,"duration":2674}},{"uid":"48cee1be3159aaf9","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/23//#testresult/48cee1be3159aaf9","status":"passed","time":{"start":1715498558574,"stop":1715498561072,"duration":2498}},{"uid":"df11f91b34803806","reportUrl":"https://slawekradzyminski.github.io/python-e2e-localstack-tests/22//#testresult/df11f91b34803806","status":"passed","time":{"start":1715498274073,"stop":1715498276563,"duration":2490}}]},"tags":[]},"source":"7f675bfbcaba31bf.json","parameterValues":[]}